"use client";
import * as React from "react";
import {
  Area,
  AreaChart,
  CartesianGrid,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";
import { motion, AnimatePresence } from "framer-motion";
import { toast } from "sonner";
import {
  AlertTriangle,
  ArrowDown,
  ArrowUp,
  Plus,
  RefreshCw,
  ScanSearch,
  Sparkles,
} from "lucide-react";
import { KpiCard } from "@/components/ui/kpi-card";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Drawer } from "@/components/ui/drawer";
import { Modal } from "@/components/ui/modal";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import { EmptyState } from "@/components/ui/empty-state";
import { formatCompact, formatCurrency, formatDate } from "@/lib/utils";

type Anomaly = {
  id: number;
  date: string;
  department: string;
  category: string;
  vendor: string;
  amount: number;
  score: number;
  reasons: string[];
};

type FData = {
  series: Array<{ month: string; actual: number | null; forecast: number | null }>;
  anomalies: Anomaly[];
  variancePct: number;
  departments: string[];
  totalCount: number;
  flaggedCount: number;
};

const CATEGORIES = ["Salaries", "Equipment", "Maintenance", "Consulting", "Supplies", "Utilities", "Software", "Vehicles"];

export function ForecastingClient() {
  const [data, setData] = React.useState<FData | null>(null);
  const [dept, setDept] = React.useState<string>("");
  const [loading, setLoading] = React.useState(false);
  const [scanRunning, setScanRunning] = React.useState(false);
  const [scanCount, setScanCount] = React.useState(0);
  const [addOpen, setAddOpen] = React.useState(false);
  const [selectedAnomaly, setSelectedAnomaly] = React.useState<Anomaly | null>(null);
  const [emailDraft, setEmailDraft] = React.useState<string | null>(null);
  const [emailLoading, setEmailLoading] = React.useState(false);

  const load = React.useCallback(async () => {
    setLoading(true);
    const url = `/api/forecasting${dept ? `?department=${encodeURIComponent(dept)}` : ""}`;
    const r = await fetch(url, { cache: "no-store" });
    const json = (await r.json()) as FData;
    setData(json);
    setLoading(false);
  }, [dept]);

  React.useEffect(() => {
    load();
  }, [load]);

  async function runScan() {
    setScanRunning(true);
    setScanCount(0);
    if (!data) return;
    const target = data.anomalies.length;
    for (let i = 0; i <= target; i++) {
      await new Promise((res) => setTimeout(res, Math.max(20, 800 / Math.max(1, target))));
      setScanCount(i);
    }
    setScanRunning(false);
    toast.success(`Scan complete. ${target} anomalies surfaced.`);
  }

  async function runForecast() {
    toast.message("Re-running forecast...");
    await new Promise((r) => setTimeout(r, 400));
    await load();
    toast.success("Forecast updated");
  }

  async function action(id: number, action: "approve" | "flag" | "email") {
    if (action === "email") {
      setEmailLoading(true);
      const r = await fetch("/api/forecasting/anomaly-action", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ id, action }),
      });
      const json = await r.json();
      setEmailDraft(json.draft);
      setEmailLoading(false);
      toast.success("Draft generated by Claude");
      return;
    }
    const r = await fetch("/api/forecasting/anomaly-action", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ id, action }),
    });
    if (r.ok) {
      toast.success(action === "approve" ? "Approved and dismissed" : "Flagged for review");
      setSelectedAnomaly(null);
      load();
    }
  }

  return (
    <div className="px-6 py-6 max-w-[1600px] mx-auto space-y-6">
      <div className="flex items-start justify-between gap-4 flex-wrap">
        <div>
          <h1 className="text-2xl font-semibold tracking-tight">Financial Forecasting</h1>
          <p className="text-sm text-muted-foreground mt-1">
            Real-time variance, anomaly detection, and 6-month cash flow projection.
          </p>
        </div>
        <div className="flex items-center gap-2">
          <select
            value={dept}
            onChange={(e) => setDept(e.target.value)}
            className="h-9 px-3 rounded-md border border-border bg-input text-sm"
          >
            <option value="">All departments</option>
            {data?.departments.map((d) => (
              <option key={d} value={d}>
                {d}
              </option>
            ))}
          </select>
          <Button variant="outline" size="sm" onClick={runForecast} disabled={loading}>
            <RefreshCw className={`w-3.5 h-3.5 ${loading ? "animate-spin" : ""}`} />
            Re-run forecast
          </Button>
          <Button size="sm" onClick={() => setAddOpen(true)}>
            <Plus className="w-3.5 h-3.5" />
            Add transaction
          </Button>
        </div>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3">
        <KpiCard
          label="Budget Variance"
          value={data ? `${data.variancePct > 0 ? "+" : ""}${data.variancePct}%` : ""}
          delta="last actual vs forecast"
          trend={data && data.variancePct < 0 ? "down" : "up"}
          icon={data && data.variancePct < 0 ? <ArrowDown className="w-4 h-4" /> : <ArrowUp className="w-4 h-4" />}
          loading={!data}
          index={0}
        />
        <KpiCard
          label="Transactions"
          value={data ? data.totalCount.toLocaleString() : ""}
          delta={dept || "All departments"}
          loading={!data}
          index={1}
        />
        <KpiCard
          label="Anomalies"
          value={data ? data.flaggedCount.toLocaleString() : ""}
          delta={data ? `${((data.flaggedCount / data.totalCount) * 100).toFixed(1)}% flagged` : ""}
          trend="up"
          icon={<AlertTriangle className="w-4 h-4" />}
          loading={!data}
          index={2}
        />
        <KpiCard
          label="Departments"
          value={data ? data.departments.length : ""}
          delta="In scope"
          loading={!data}
          index={3}
        />
      </div>

      <Card>
        <CardHeader className="flex-row items-center justify-between">
          <div>
            <CardTitle>Cash flow forecast</CardTitle>
            <p className="text-xs text-subtle mt-0.5">
              Linear regression with seasonal adjustment, 6-month horizon
            </p>
          </div>
          <div className="flex items-center gap-4 text-xs">
            <span className="flex items-center gap-1.5">
              <span className="h-2 w-2 rounded-full bg-primary" />
              Actual
            </span>
            <span className="flex items-center gap-1.5">
              <span className="h-2 w-2 rounded-full bg-success" />
              Forecast
            </span>
          </div>
        </CardHeader>
        <CardContent>
          {!data ? (
            <Skeleton className="h-[320px]" />
          ) : (
            <div className="h-[320px]">
              <ResponsiveContainer width="100%" height="100%">
                <AreaChart data={data.series}>
                  <defs>
                    <linearGradient id="a1" x1="0" y1="0" x2="0" y2="1">
                      <stop offset="0%" stopColor="#3B82F6" stopOpacity={0.35} />
                      <stop offset="100%" stopColor="#3B82F6" stopOpacity={0} />
                    </linearGradient>
                    <linearGradient id="a2" x1="0" y1="0" x2="0" y2="1">
                      <stop offset="0%" stopColor="#10B981" stopOpacity={0.25} />
                      <stop offset="100%" stopColor="#10B981" stopOpacity={0} />
                    </linearGradient>
                  </defs>
                  <CartesianGrid stroke="var(--border)" strokeDasharray="3 3" vertical={false} />
                  <XAxis dataKey="month" stroke="var(--subtle)" tick={{ fontSize: 11 }} tickLine={false} axisLine={false} />
                  <YAxis
                    stroke="var(--subtle)"
                    tick={{ fontSize: 11 }}
                    tickLine={false}
                    axisLine={false}
                    tickFormatter={(v) => `$${formatCompact(Number(v))}`}
                  />
                  <Tooltip
                    contentStyle={{
                      background: "var(--surface)",
                      border: "1px solid var(--border)",
                      borderRadius: 8,
                      fontSize: 12,
                    }}
                    formatter={(v) => formatCurrency(Number(v))}
                  />
                  <Area type="monotone" dataKey="actual" stroke="#3B82F6" strokeWidth={2.2} fill="url(#a1)" />
                  <Area
                    type="monotone"
                    dataKey="forecast"
                    stroke="#10B981"
                    strokeWidth={2.2}
                    strokeDasharray="4 4"
                    fill="url(#a2)"
                  />
                </AreaChart>
              </ResponsiveContainer>
            </div>
          )}
        </CardContent>
      </Card>

      <Card>
        <CardHeader className="flex-row items-center justify-between">
          <div>
            <CardTitle>Anomaly panel</CardTitle>
            <p className="text-xs text-subtle mt-0.5">
              Statistical outliers, duplicates, round-number invoices
            </p>
          </div>
          <Button variant="outline" size="sm" onClick={runScan} disabled={scanRunning}>
            {scanRunning ? <ScanSearch className="w-3.5 h-3.5 animate-pulse" /> : <Sparkles className="w-3.5 h-3.5" />}
            {scanRunning ? `Scanning... ${scanCount}` : "Run anomaly scan"}
          </Button>
        </CardHeader>
        <CardContent className="space-y-2">
          {!data && [0, 1, 2].map((i) => <Skeleton key={i} className="h-14" />)}
          {data && data.anomalies.length === 0 && (
            <EmptyState
              icon={<AlertTriangle className="w-4 h-4" />}
              title="No anomalies detected"
              description="The scan found no irregular transactions in the selected scope."
            />
          )}
          {data?.anomalies.map((a, i) => (
            <motion.div
              key={a.id}
              initial={{ opacity: 0, y: 4 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: Math.min(i * 0.02, 0.2) }}
              onClick={() => setSelectedAnomaly(a)}
              className="group flex items-center gap-3 p-3 rounded-md border border-border hover:bg-surface-2 cursor-pointer transition-colors"
            >
              <span className="flex h-8 w-8 items-center justify-center rounded bg-warning/10 text-warning">
                <AlertTriangle className="w-3.5 h-3.5" />
              </span>
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2 flex-wrap">
                  <p className="text-sm font-medium truncate">{a.vendor}</p>
                  <Badge variant="warning">{a.category}</Badge>
                  <Badge variant="outline">{a.department}</Badge>
                </div>
                <p className="text-xs text-muted-foreground mt-0.5 truncate">{a.reasons.join(" • ")}</p>
              </div>
              <div className="text-right">
                <div className="text-sm font-medium tabular-nums">{formatCurrency(a.amount)}</div>
                <div className="text-xs text-subtle">{formatDate(a.date)}</div>
              </div>
            </motion.div>
          ))}
        </CardContent>
      </Card>

      <AddTxModal open={addOpen} onOpenChange={setAddOpen} departments={data?.departments || []} onSaved={load} />

      <Drawer
        open={!!selectedAnomaly}
        onOpenChange={(v) => {
          if (!v) {
            setSelectedAnomaly(null);
            setEmailDraft(null);
          }
        }}
        title="Anomaly detail"
        description={selectedAnomaly?.vendor}
      >
        {selectedAnomaly && (
          <div className="space-y-5">
            <div className="grid grid-cols-2 gap-3">
              <Field label="Vendor" value={selectedAnomaly.vendor} />
              <Field label="Amount" value={formatCurrency(selectedAnomaly.amount)} />
              <Field label="Date" value={formatDate(selectedAnomaly.date)} />
              <Field label="Category" value={selectedAnomaly.category} />
              <Field label="Department" value={selectedAnomaly.department} />
              <Field label="Score" value={(selectedAnomaly.score * 100).toFixed(0) + "%"} />
            </div>
            <div>
              <h3 className="text-xs font-medium uppercase tracking-wider text-muted-foreground mb-2">
                Reasons
              </h3>
              <ul className="space-y-1.5">
                {selectedAnomaly.reasons.map((r, i) => (
                  <li key={i} className="text-sm flex items-start gap-2">
                    <span className="mt-1.5 h-1 w-1 rounded-full bg-warning shrink-0" />
                    {r}
                  </li>
                ))}
              </ul>
            </div>
            <div className="grid grid-cols-3 gap-2">
              <Button variant="success" size="sm" onClick={() => action(selectedAnomaly.id, "approve")}>
                Approve
              </Button>
              <Button variant="destructive" size="sm" onClick={() => action(selectedAnomaly.id, "flag")}>
                Flag
              </Button>
              <Button variant="secondary" size="sm" onClick={() => action(selectedAnomaly.id, "email")} disabled={emailLoading}>
                <Sparkles className="w-3 h-3" />
                {emailLoading ? "Drafting..." : "Email"}
              </Button>
            </div>
            <AnimatePresence>
              {emailDraft && (
                <motion.div
                  initial={{ opacity: 0, y: 4 }}
                  animate={{ opacity: 1, y: 0 }}
                  className="rounded-md border border-border bg-surface-2 p-4"
                >
                  <h3 className="text-xs font-medium uppercase tracking-wider text-muted-foreground mb-2">
                    Draft email
                  </h3>
                  <pre className="text-sm whitespace-pre-wrap font-sans leading-relaxed">{emailDraft}</pre>
                </motion.div>
              )}
            </AnimatePresence>
          </div>
        )}
      </Drawer>
    </div>
  );
}

function Field({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <div className="text-[10px] uppercase tracking-wider text-subtle">{label}</div>
      <div className="text-sm font-medium mt-0.5">{value}</div>
    </div>
  );
}

function AddTxModal({
  open,
  onOpenChange,
  departments,
  onSaved,
}: {
  open: boolean;
  onOpenChange: (v: boolean) => void;
  departments: string[];
  onSaved: () => void;
}) {
  const [form, setForm] = React.useState({
    date: new Date().toISOString().slice(0, 10),
    department: departments[0] || "",
    category: CATEGORIES[0],
    vendor: "",
    amount: "",
  });
  const [saving, setSaving] = React.useState(false);

  React.useEffect(() => {
    if (departments[0] && !form.department) setForm((f) => ({ ...f, department: departments[0] }));
  }, [departments, form.department]);

  async function submit() {
    if (!form.vendor || !form.amount) {
      toast.error("Vendor and amount required");
      return;
    }
    setSaving(true);
    const r = await fetch("/api/forecasting", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ ...form, amount: Number(form.amount) }),
    });
    setSaving(false);
    if (r.ok) {
      toast.success("Transaction added and forecast updated");
      onOpenChange(false);
      setForm({ ...form, vendor: "", amount: "" });
      onSaved();
    } else {
      toast.error("Failed to save");
    }
  }

  return (
    <Modal open={open} onOpenChange={onOpenChange} title="Add transaction" description="Recompute the forecast with one record." size="md">
      <div className="space-y-3">
        <div className="grid grid-cols-2 gap-3">
          <label className="block">
            <span className="text-xs text-muted-foreground">Date</span>
            <Input type="date" value={form.date} onChange={(e) => setForm({ ...form, date: e.target.value })} />
          </label>
          <label className="block">
            <span className="text-xs text-muted-foreground">Amount (CAD)</span>
            <Input
              type="number"
              step="0.01"
              placeholder="0.00"
              value={form.amount}
              onChange={(e) => setForm({ ...form, amount: e.target.value })}
            />
          </label>
        </div>
        <label className="block">
          <span className="text-xs text-muted-foreground">Department</span>
          <select
            value={form.department}
            onChange={(e) => setForm({ ...form, department: e.target.value })}
            className="h-9 w-full px-3 rounded-md border border-border bg-input text-sm"
          >
            {departments.map((d) => (
              <option key={d} value={d}>
                {d}
              </option>
            ))}
          </select>
        </label>
        <label className="block">
          <span className="text-xs text-muted-foreground">Category</span>
          <select
            value={form.category}
            onChange={(e) => setForm({ ...form, category: e.target.value })}
            className="h-9 w-full px-3 rounded-md border border-border bg-input text-sm"
          >
            {CATEGORIES.map((c) => (
              <option key={c} value={c}>
                {c}
              </option>
            ))}
          </select>
        </label>
        <label className="block">
          <span className="text-xs text-muted-foreground">Vendor</span>
          <Input
            placeholder="Acme Industrial"
            value={form.vendor}
            onChange={(e) => setForm({ ...form, vendor: e.target.value })}
          />
        </label>
        <div className="flex justify-end gap-2 pt-2">
          <Button variant="ghost" onClick={() => onOpenChange(false)}>
            Cancel
          </Button>
          <Button onClick={submit} disabled={saving}>
            {saving ? "Saving..." : "Save"}
          </Button>
        </div>
      </div>
    </Modal>
  );
}
